# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145db34c4aeda3532137aa155f9b0f4f47b38427a4297edab7340aeb387e6363a2599cfd0b8ab0048a39feec3d01890959d6ca0e953e594637b06944e08a0009

test:
  secret_key_base: cbf5e3fd9c59763aa48a8b6b056749c938fac96916723aad2eccfad59f1532c64eaa46d26a1bfee1dbf2b40ad8602ed05813af67ff1fd97af58fd63fe4a5a96d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
